version: '3'
services:

  redis1:
    image: redis:5.0-alpine
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - CLIENTPORT=6379
      - CLIENTHOST=192.168.137.101
      - MASTERHOST=
      - MASTERPORT=
    volumes:
      - "../../redis-data/redis1:/data"
    restart: always

  redis2:
    image: redis:5.0-alpine
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
        - REQUIREPASS=password1234
        - CLIENTPORT=6380
        - CLIENTHOST=192.168.137.101
        - MASTERHOST=6379
        - MASTERPORT=192.168.137.101
    volumes:
      - "../../redis-data/redis2:/data"
    restart: always

  redis3:
    image: redis:5.0-alpine
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - CLIENTPORT=6381
      - CLIENTHOST=192.168.137.101
      - MASTERHOST=6379
      - MASTERPORT=192.168.137.101
    volumes:
      - "../../redis-data/redis3:/data"
    restart: always
