version: '3'
services:

  redis-master:
     image: redis:4.0.8-alpine
     build: ../Dockerfile
     network_mode: "host"
     environment:
      - REQUIREPASS=1234
      - CLIENTPORT=6379
      - CLIENTHOST=127.0.0.1
      - MASTERHOST=
      - MASTERPORT=
     volumes:
      - "./redis-data/master:/data"
     restart: always
      
  redis-slave1:
     image: redis:4.0.8-alpine
     build: ../Dockerfile
     network_mode: "host"
     environment:
      - REQUIREPASS=1234
      - CLIENTHOST=127.0.0.1
      - CLIENTPORT=6380
      - MASTERHOST=127.0.0.1
      - MASTERPORT=6379
     volumes:
      - "./redis-data/slave1:/data"
     restart: always
      
  redis-slave2:
     image: redis:4.0.8-alpine
     build: ../Dockerfile
     network_mode: "host"
     environment:
      - REQUIREPASS=1234
      - CLIENTHOST=127.0.0.1
      - CLIENTPORT=6381
      - MASTERHOST=127.0.0.1
      - MASTERPORT=6379
     volumes:
      - "./redis-data/slave2:/data"
     restart: always

